Fix lint issues
ExtensionEngine/lms-starter pull request #161
Opened 2021-01-31 15:04 UTC by mcapeta

2021-02-04 11:16 UTC, zcuric commented
👍🏻

2021-02-18 10:17 UTC, lukasaric requested changes

2021-02-18 10:17 UTC, lukasaric commented on server/user/user.model.js
> +    return this.role === role.ADMIN;
`Role`?

2021-02-24 08:53 UTC, malizeus approved these changes

2021-02-24 09:45 UTC, merged