User invitation resend
ExtensionEngine/lms-starter pull request #50
Opened 2018-11-05 15:05 UTC by borna223

It is now possible to reinvite users.

2018-11-06 03:25 UTC, vladimyr requested changes

2018-11-06 03:25 UTC, vladimyr commented on client/admin/components/users/index.vue
> +        :message="confirmation.message"
Instead of listing all `confirmation` properties you could simply use:
```html
v-bind="confirmation"
```

2018-11-06 03:25 UTC, vladimyr commented on client/admin/components/users/index.vue
> +        @confirmed="confirmation.event"/>
`confirmed` is an event, what you have here is callback or listener :point_up:

2018-11-06 03:25 UTC, vladimyr commented on client/admin/components/users/index.vue
> +        message: ''
I understand appeal of listing all properties for documentation purposes but you have it listed few lines bellow too. Only thing that you really need here is:
```js
confirmation: { show: false }
```

2018-11-06 03:25 UTC, vladimyr commented on server/config.js
> +    tls: !!process.env.EMAIL_TLS
Use `Boolean(<arg>)` form of casting to boolean.

2018-11-06 07:12 UTC, underscope requested changes

2018-11-06 07:12 UTC, underscope commented on server/user/user.controller.js
> +function reinvite({ params, origin }, res) {
Please update naming (Except on user dialog button) to just `invite`

2018-11-06 07:12 UTC, underscope commented on client/admin/components/users/index.vue
> +              <v-icon @click="reinviteUser(item)" small class="ml-3">mdi-email</v-icon>
Remove reinvite from user list and make it available solely from user modal (top right corner).

2018-11-07 18:56 UTC, vladimyr approved these changes

2018-11-08 15:04 UTC, merged