Enrollments search
ExtensionEngine/lms-starter pull request #53
Opened 2018-11-07 09:04 UTC by borna223

It is now possible to search for enrolled users.

2018-11-07 12:16 UTC, franosincic commented on client/admin/components/Program/Enrollments/index.vue
> +    message() {
maybe tableMessages?

2018-11-07 12:16 UTC, franosincic commented on client/admin/components/Program/Enrollments/index.vue
> +        ? 'No results.'
maybe 'There are no such learners.'?

2018-11-11 22:25 UTC, underscope requested changes

2018-11-11 22:25 UTC, underscope commented on client/admin/components/Program/Enrollments/index.vue
> +    tableMessages() {
It shouldn't be plural (only one message is returned). Frano had a good point regarding naming, consider improving it even more => something like  `noEnrollmentsMessage` or something else that will describe it better 😉

2018-11-11 22:25 UTC, underscope commented on client/admin/components/Program/Enrollments/index.vue
> +      const params = { programId: this.programId, filter: this.filter };
Pick might be cleaner 💅

2018-11-11 22:25 UTC, underscope commented on server/enrollment/enrollment.controller.js
> +  const include = { model: User, as: 'student', where: {} };
You can omit where here and define it in if bellow if needed

2018-11-11 22:25 UTC, underscope commented on server/enrollment/enrollment.controller.js
> +  const opts = { where: { [Op.and]: cond }, include: [include], ...options };
Rename first `include` to `includeStudent` in order to avoid `include: [include]`;

2018-11-12 10:58 UTC, franosincic commented on client/admin/components/Program/Enrollments/index.vue
> -      :value="!isLoading && !totalItems"
you dont need isLoading prop anymore

2018-11-12 10:58 UTC, franosincic commented on client/admin/components/Program/Enrollments/index.vue
> +        ? `Your search for "${this.filter}" found no results.`
use single-quotes

2018-11-12 13:27 UTC, vladimyr requested changes

2018-11-12 13:27 UTC, vladimyr commented on client/admin/components/Program/Enrollments/index.vue
> +    }
Please move this outside of component:
```js
const noEnrollmentsMessage = (search = false) => search
  ? `No search results for given filter: "${this.filter}"`
  : 'Click on the button above to enroll learner.'
```
and _mix_ it back in:
```js
  computed: {
    defaultPage,
    noEnrollmentsMessage
  }
```

2018-11-12 13:27 UTC, vladimyr commented on client/admin/components/Program/Enrollments/index.vue
> +  background-color: #fff;
Use shorthand: `background: #fff;` :bowtie:

2018-11-12 13:27 UTC, vladimyr commented on server/enrollment/enrollment.controller.js
> +  const includeStudent = { model: User, as: 'student' };
```js
const include = [{ model: User, as: 'student' }];
```
and later on:
```js
const opts = { where: { [Op.and]: cond }, include, ...options };
```

2018-11-12 13:27 UTC, vladimyr commented on server/enrollment/enrollment.controller.js
> +  it => ({ [it]: { [Op.iLike]: `%${q}%` } }));
This is second time I'm seeing this through codebase so let's put it inside User model as some sort of search scope. For reference how to do it you can use following link: https://github.com/sequelize/sequelize/issues/6440#issuecomment-321446078

2018-11-12 13:27 UTC, vladimyr commented on client/admin/components/Program/Enrollments/index.vue
> +      confirmationAction: null
While you are _here_ group those two into `confirmation` object :bowtie:

2018-11-12 13:28 UTC, vladimyr commented on client/admin/components/Program/Enrollments/index.vue
> +        ? `Your search for "${this.filter}" found no results.`
Actually this should be written using double quotes because it is user facing string ☝️

2018-11-13 08:32 UTC, vladimyr commented on client/admin/components/Program/Enrollments/index.vue
> +    }
@vladimyr Go home you are drunk 🤦

2018-11-13 20:06 UTC, vladimyr commented on client/admin/components/Program/Enrollments/index.vue
> +      this.confirmation.action = () => api.remove(enrollment);
When you have more than one property to assign use `Object.assign`:
```js
Object.assign(this, { dialog: true, action: () => api.remove(enrollment) });
```

2018-11-13 20:11 UTC, vladimyr requested changes

2018-11-13 20:11 UTC, vladimyr commented on server/enrollment/enrollment.controller.js
> +  if (filter) include[0].where = { [Op.or]: createFilter(filter) };
How about:
```js
const where =  filter ? { [Op.or]: createFilter(filter) } : {};
const include = [{ model: User, as: 'student', where }];
```

2018-11-15 17:46 UTC, merged