Unique program names
ExtensionEngine/lms-starter pull request #54
Opened 2018-11-08 14:36 UTC by borna223

Program names have to be unique from now on.

2018-11-12 13:33 UTC, vladimyr requested changes

2018-11-12 13:33 UTC, vladimyr commented on server/program/program.model.js
> +const { Op } = Sequelize;
You can destructure `Op` from `require('sequelize');` :bowtie:

2018-11-12 13:33 UTC, vladimyr commented on server/program/program.model.js
> +        set(value) { this.setDataValue('name', trim(value)); }
Ok, but why? You could set default value to make sure it is string and just use native trim? 🤔

2018-11-13 20:04 UTC, vladimyr requested changes

2018-11-13 20:04 UTC, vladimyr commented on client/common/validation.js
> +    const [fetchedProgram] = await api.fetch({ params: { name, deleted: true } });
You don't need to fetch if program name is same as initial value:
```js
if (program && program.name === name) return true;
```
which consequentially makes id checking obsolete 😉

2018-11-13 20:04 UTC, vladimyr commented on server/program/program.controller.js
> +  if (name) where.name = { [Op.iLike]: name };
This should be trimmed? 🤔

2018-11-14 08:48 UTC, borna223 commented on client/common/validation.js
> +    const [fetchedProgram] = await api.fetch({ params: { name, deleted: true } });
But what if new program name differs only in case sensitivity?

2018-11-14 09:12 UTC, vladimyr commented on client/common/validation.js
> +    const [fetchedProgram] = await api.fetch({ params: { name, deleted: true } });
In that case do case insensitive comparison?

2018-11-14 15:35 UTC, merged