Multiselect users
ExtensionEngine/lms-starter pull request #63
Opened 2018-11-21 11:51 UTC by borna223

It is now possible to select (or deselect) multiple users by holding down `shift` key.

2018-11-28 03:36 UTC, vladimyr requested changes

2018-11-28 03:36 UTC, vladimyr commented on client/admin/components/users/index.vue
> +                  @change="$event ? selectMultiple() : deselectMultiple(props.item.id)"
Too much programming in template, extract this to `onToggle` method :bowtie:

2018-11-28 03:36 UTC, vladimyr commented on client/admin/components/users/index.vue
> +      if (this.multiSelect && this.selectedUsers.length >= 2) {
Before I start with _serious_ review toggle those conditions to avoid unnecessary indent...

2021-01-20 15:26 UTC, underscope commented
Closing it until we have scenario for it / extract relevant controls

2021-01-20 15:26 UTC, closed without merging