Update poi to v12
ExtensionEngine/lms-starter pull request #73
Opened 2018-12-20 16:49 UTC by borna223

Updated poi to v12.

2019-01-15 13:14 UTC, vladimyr requested changes

2019-01-15 13:14 UTC, vladimyr commented on poi.config.js
> +const aliases = { '@': path.resolve(__dirname, './client') };
Don't inline this, we might have larger map of those in future.

2019-01-15 13:14 UTC, vladimyr commented on poi.config.js
> -  },
Why did you remove this?

2019-01-15 13:14 UTC, vladimyr commented on poi.config.js
> +    config.resolve.extensions.merge(extensions);
So this is now required? 🤔

2019-01-23 14:26 UTC, borna223 commented on poi.config.js
> +    config.resolve.extensions.merge(extensions);
https://github.com/egoist/poi/pull/528

2019-01-23 22:26 UTC, vladimyr commented on poi.config.js
> +    '@poi/eslint'
@borna223 This would work both in `dev` and `prod` mode? Just double checkin...

2019-01-23 22:28 UTC, vladimyr requested changes

2019-01-23 22:28 UTC, vladimyr commented on poi.config.js
> +    if (!process.argv.includes('--bundle-report')) return;
Um, don't do this. Use [`minimist`](https://npm.im/minimist) instead and check if flag is specified.

2019-01-27 16:40 UTC, merged