Disabled deleting own account
ExtensionEngine/lms-starter pull request #97
Opened 2019-02-20 14:44 UTC by rkusan00

- removed option to delete account of the current user in admin menu
- added tooltip for the user info

2019-02-20 15:56 UTC, zcuric commented on client/admin/components/common/Navbar.vue
> +      return this.user.firstName + ' ' + this.user.lastName;
You can use [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) here. 
```js
return `${this.user.firstName} ${this.user.lastName}`
```
Maybe even use [object destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Object_destructuring)
```js
const { firstName, lastName } = this.user;
return `${firstName} ${lastName}`;
```

2019-02-20 15:57 UTC, zcuric commented on client/admin/components/users/index.vue
> +    ...mapState('auth', ['user'])
Move `...mapState('auth', ['user'])` at top of the object, so you don't accidentally override previously computed props.

2019-02-21 01:08 UTC, vladimyr requested changes

2019-02-21 01:08 UTC, vladimyr commented on client/admin/components/common/Navbar.vue
> +      return '${firstName} ${lastName}';s
Hm, you have typo here :bowtie:

2019-02-21 01:08 UTC, vladimyr commented on client/admin/components/users/index.vue
> +                </v-icon>
Don't remove icon completely, fade it away and disable click handler :bowtie:

2019-02-21 10:21 UTC, vladimyr requested changes

2019-02-21 10:21 UTC, vladimyr commented on client/admin/components/users/index.vue
> +                  :disabled="user.id == props.item.id"
Triple equals please :bowtie:

2019-02-21 10:21 UTC, vladimyr commented on client/admin/components/users/index.vue
> +                </v-icon>
Does setting `disabled` disables click handler too?

2019-02-26 04:12 UTC, vladimyr commented
@kjuej Please verify this one.

2019-06-04 11:07 UTC, zcuric commented
@kjuej ☝️

2019-06-04 15:36 UTC, merged